version: '3'

services:
  server:
    image: gudangmovie-server-go
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      - DB_USER=root
      - DB_HOST=database
      - DB_NAME=gudangmovie-server
      - JWT_SECRET="hdWPRahErNM7uAlTPe342JEiXtVQxyyp"
      - JWT_SECRET_REFRESH="hEcI74RpqfUVgEEM0hTwZDF6Ypie4zWP"
      - GIN_MODE=release

  database:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gudangmovie-server
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      interval: 10s
      start_period: 40s
      retries: 3